nav:
  - Start: index.md
  - Analysis:
      - Überblick: analysis/index.md
  - Analytische Geometrie:
      - Überblick: ag/index.md
      - Geradengleichung: ag/geraden.md
  - Stochastik:
      - Überblick: stochastik/index.md
